name: mana_yatra_admin
description: "Mana Yatra Admin Dashboard - Platform management"
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.7
  cloud_functions: ^5.6.2
  firebase_messaging: ^15.2.10
  # State Management
  flutter_riverpod: ^2.6.1
  # Routing
  go_router: ^15.1.2
  # UI & Charts
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  responsive_framework: ^1.5.1
  # Utilities
  intl: ^0.20.2
  http: ^1.2.1
  csv: ^6.0.0
  url_launcher: ^6.3.1
  timeago: ^3.7.0
  flutter_native_splash: ^2.4.7
  firebase_database: ^11.3.10
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  google_maps_flutter: ^2.14.2
  pdf: ^3.12.0
  printing: ^5.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/gaman_logo.png"
  adaptive_icon_foreground: "assets/images/logo/foreground.png"
  adaptive_icon_background: "assets/images/logo/background.png"

flutter_native_splash:
  android: true
  ios: true

  color: "#FFcc00"
  image: "assets/images/logo/splashscreen.png"
  
  fullscreen: true
  android_12:
    color: "#FFcc00"
    image: "assets/images/logo/android12splash.png"
    

flutter:
  uses-material-design: true
  assets:
    - assets/images/map_icons/
